### PR TITLE
Fix issue #21.

### PR DESCRIPTION
**Pull request by gillesfabio**

### CODE REVIEW

**Comment by pquentin** [comment]
I'm afraid this doesn't fix the issue: you now have n JS timers, but only one moment.js time, and only one place to display the time left. It doesn't make sense to be on a break and on a pomodoro at the same time: the fix is really to clear the previous timer when setting a new one.

**Comment by gillesfabio** [comment]
@pquentin Thanks for your review! The fix fixed the issue but, indeed, was not the KISS way to do so (see `timers` as `intervals`, and not "timers" properly). Anyway. I agree with you. I simply added a `clearInterval`. Much relevant.

**Comment by pquentin** [comment]
The new version looks great. :) Thank you!

**Comment by gillesfabio** [comment]
Squashed commits.

**Comment by gillesfabio** [comment]
Will propose a better PR soon.

**Pull request closed without merging**
